# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ 3.x ]
  pull_request:
    branches: [ 3.x ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CI_PULL_REQUEST: ${{ github.event.number }}
      JAVADOCS_TOKEN: ${{ secrets.JAVADOCS_TOKEN }} 
      CI_BUILD_NUMBER: ${{ github.run_number }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Grant execute permission for push
      run: chmod +x push.sh
    - name: Build with Gradle
      run: ./gradlew build javadoc --stacktrace
    - name: Upload to Codecov  
      uses: codecov/codecov-action@v1
    - name: Push Javadocs
      run: ./push.sh
